#生产环境配置

server:
  # 服务端口
  port: 5004

spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    username: root
    password: Z2TzT5jzXCi5paZY
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.75.121:3306/veronica_blog?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
  sql:
    init:
      enabled: false

# 开启权限拦截
auth:
  enabled: true

# 开启请求日志记录
request-log:
  enabled: true



